Release 1.0.2: Bug fix for custom requests and selected facet range
- Fix bug where custom requests get a randomly generated API key
- Make selected range on range facets optional
- Rename `getScopedResults` to `getScopedResult`
- Deprecate `getScopedResults`
- Improve reporting of server errors

DETAILS:

* Fix bug where custom requests get a randomly generated API key

When performing custom requests, the implementation accidentally attempted to
send a user ID as the API key. Since custom requests generally aren't performed
by the end user, no user ID existed and a new one was generated for every
request.

* Make selected range on range facets optional

The API allows the selected range object to be absent, but if it is present,
then both keys are required. The library misinterpreted this requirement and
forced the range object with both parameters to be present. This is now fixed.

* Rename `getScopedResults` to `getScopedResult`
* Deprecate `getScopedResults`

This reflects the expectation that `getScopedResult` will only return a single
query result. The old method can still be used, but will generate a deprecation
warning.

* Improve reporting of server errors

The default `ApiException` thrown by the generated low-level code could truncate
the error message at the most inconvenient locations:

```
{
"code": 400,
"status": "BadRequest",
"title": "Request is invalid or malformed",
"detail": "Missing required property
(truncated...)
```

At now the error message should be slightly more descriptive of the issue:

```
Fatal error: Uncaught Loop54\API\ClientException:
[400 BadRequest] Request is invalid or malformed:
Missing required property "min".
(Applies to: request.resultsOptions.facets[1].selected)
```